### ISSUE TITLE
features download

### ISSUE THREAD

**Issue by zzzmy0826** [menorashid/action_graphs#4]
Hi, thank you very much for your excellent work, I am currently doing research on temporal action detection. i cant download features from your provided link about ActivityNet dataset, something broken. Could you show me another link?

**Comment by menorashid** [comment]
hey. i'll try to get them up this weekend.

Maheen

**Comment by zzzmy0826** [comment]
Thank you very much and look forward to your uploading features.

Mengyao

**Comment by menorashid** [comment]
Hi Mengyao

I’m sorry I haven’t uploaded the features yet. I am away on holiday right
now and my internet is bad. I use the same features as provided by Sujoy
Paul for the WTALC paper. If you’d like to use those instead (you can look
at the provided train and test txt files to figure out the splits) that
would be great. Otherwise I’ll try to work something out. Sorry for the
delay!

Maheen

**Comment by menorashid** [comment]
Hello. The activitynet features are uploaded now.
